version: '3'

services:
  backend:
    build:
      context: ./websocket
    ports:
      - "8080:8080"
    environment:
      - RedisConnection=
      - DefaultConnection=
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge